module GestImpr {

    interface Imprimante {
      short printDocument ( in string n,
          out long t);
    };
    interface AdminImprimante {
       attribute long etat;
    };
    interface  ImprimantePlus : Imprimante, AdminImprimante {
	const boolean boolval = false;
	const long constval1 = 0x0A;
	const octet constval2 = 0x0b;
	const long constval3 = constval1 + constval2 * 2; // must give 32
	const string constval4 = "constval1 = " + constval1; // must give "constval1 = 10"
	const float factor = (10.0 - 6.5) * 3.91; // must give 13.685
      any tachesEnCours();
       readonly attribute short tacheCour;
       void envoiRapide ( in string n);
    };
};